mqtt:
  broker: "tcp://127.0.0.1:1883"
  client_id: "greenhouse-controller-01"
  username: "iot_user"
  password: "secure_password_123"
  qos: 1
  keep_alive: 90
  clean_session: true
  topics:
    command: "greenhouse/{gh_id}/command"
    metrics: "greenhouse/{gh_id}/metrics"

database:
  path: "data/greenhouse.db"

admin:
  username: "admin"
  password: "StrongAdminPassword"